# Generated by Django 4.2.4 on 2023-08-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapplication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='country_origin',
            new_name='country_of_origin',
        ),
    ]
