# Generated by Django 4.2.4 on 2023-08-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapplication', '0003_alter_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='date',
        ),
    ]
